// Package pool provides a generic, type-safe wrapper around sync.Pool
// that constrains stored objects to types implementing Reset().
// Before an object is returned to the pool via Put, its Reset method is
// called automatically so the next caller always gets a clean instance.
package pool

import "sync"

// Resettable is satisfied by any type that exposes a Reset() method.
// It matches the signature generated by cmd/reset.
type Resettable interface {
	Reset()
}

// Pool is a generic pool of Resettable objects backed by sync.Pool.
// T must be a type (typically a pointer) that implements Reset().
type Pool[T Resettable] struct {
	p sync.Pool
}

// New creates a Pool that uses newFunc to allocate fresh instances
// whenever the pool is empty.
func New[T Resettable](newFunc func() T) *Pool[T] {
	return &Pool[T]{
		p: sync.Pool{
			New: func() any { return newFunc() },
		},
	}
}

// Get returns an object from the pool, allocating a new one if needed.
func (p *Pool[T]) Get() T {
	return p.p.Get().(T)
}

// Put resets v and returns it to the pool for reuse.
func (p *Pool[T]) Put(v T) {
	v.Reset()
	p.p.Put(v)
}
