// Package main is a code generator that creates Reset() methods for structs
// annotated with the // generate:reset comment.
//
// Usage:
//
//	go run ./cmd/reset/...
//
// For each package found under the current directory the generator writes a
// reset.gen.go file containing a Reset() method for every annotated struct.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

// primitiveZero maps builtin primitive type names to their zero-value literals.
var primitiveZero = map[string]string{
	"int": "0", "int8": "0", "int16": "0", "int32": "0", "int64": "0",
	"uint": "0", "uint8": "0", "uint16": "0", "uint32": "0", "uint64": "0",
	"uintptr": "0", "byte": "0", "rune": "0",
	"float32": "0", "float64": "0",
	"complex64": "0", "complex128": "0",
	"bool":   "false",
	"string": `""`,
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		if path != root {
			name := info.Name()
			if len(name) > 0 && (name[0] == '.' || name == "vendor" || name == "testdata") {
				return filepath.SkipDir
			}
		}
		return processDir(path)
	}); err != nil {
		log.Fatal(err)
	}
}

type structInfo struct {
	name   string
	fields []*ast.Field
}

func processDir(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		n := fi.Name()
		return !strings.HasSuffix(n, "_test.go") && n != "reset.gen.go"
	}, parser.ParseComments)
	if err != nil {
		return nil // skip directories that don't parse cleanly
	}

	for pkgName, pkg := range pkgs {
		var structs []*structInfo
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.TYPE {
					continue
				}
				gdAnnotated := hasResetAnnotation(gd.Doc)
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					if !gdAnnotated && !hasResetAnnotation(ts.Doc) {
						continue
					}
					si := &structInfo{name: ts.Name.Name}
					for _, f := range st.Fields.List {
						si.fields = append(si.fields, f)
					}
					structs = append(structs, si)
				}
			}
		}
		if len(structs) == 0 {
			continue
		}
		src, err := generateSource(pkgName, structs)
		if err != nil {
			return fmt.Errorf("generate %s: %w", dir, err)
		}
		out := filepath.Join(dir, "reset.gen.go")
		if err := os.WriteFile(out, src, 0o644); err != nil {
			return err
		}
		fmt.Printf("generated %s\n", out)
	}
	return nil
}

// hasResetAnnotation reports whether doc contains a "// generate:reset" line.
func hasResetAnnotation(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == "generate:reset" {
			return true
		}
	}
	return false
}

// recvName returns the lowercase first letter of typeName for use as a receiver.
func recvName(typeName string) string {
	for _, r := range typeName {
		if unicode.IsLetter(r) {
			return string(unicode.ToLower(r))
		}
	}
	return "s"
}

func generateSource(pkgName string, structs []*structInfo) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by reset; DO NOT EDIT.\n\npackage %s\n", pkgName)
	for _, s := range structs {
		recv := recvName(s.name)
		fmt.Fprintf(&buf, "\n// Reset resets all fields of %s to their zero values.\nfunc (%s *%s) Reset() {\n", s.name, recv, s.name)
		fmt.Fprintf(&buf, "\tif %s == nil {\n\t\treturn\n\t}\n", recv)
		for _, field := range s.fields {
			for _, fn := range fieldNames(field) {
				if line := resetLine(recv, fn, field.Type); line != "" {
					fmt.Fprintf(&buf, "\t%s\n", line)
				}
			}
		}
		fmt.Fprintf(&buf, "}\n")
	}
	return format.Source(buf.Bytes())
}

// fieldNames returns the names of a struct field, handling embedded types.
func fieldNames(f *ast.Field) []string {
	if len(f.Names) > 0 {
		names := make([]string, len(f.Names))
		for i, n := range f.Names {
			names[i] = n.Name
		}
		return names
	}
	if name := embeddedTypeName(f.Type); name != "" {
		return []string{name}
	}
	return nil
}

// embeddedTypeName extracts the field name from an embedded (anonymous) type.
func embeddedTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return embeddedTypeName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	}
	return ""
}

// resetLine returns the Go statement that resets a single field to its zero value.
func resetLine(recv, field string, typ ast.Expr) string {
	ref := recv + "." + field
	switch t := typ.(type) {
	case *ast.Ident:
		if zero, ok := primitiveZero[t.Name]; ok {
			return ref + " = " + zero
		}
		// Named non-primitive type: delegate via Reset() interface if available.
		return fmt.Sprintf("if _r, _ok := any(&%s).(interface{ Reset() }); _ok { _r.Reset() }", ref)
	case *ast.SelectorExpr:
		// Qualified type (pkg.Type): delegate via Reset() interface if available.
		return fmt.Sprintf("if _r, _ok := any(&%s).(interface{ Reset() }); _ok { _r.Reset() }", ref)
	case *ast.ArrayType:
		if t.Len == nil {
			// Slice: retain backing array, reset length to zero.
			return ref + " = " + ref + "[:0]"
		}
		// Fixed-size array: leave unchanged.
		return ""
	case *ast.MapType:
		return "clear(" + ref + ")"
	case *ast.StarExpr:
		return ptrResetLine(ref, t.X)
	case *ast.InterfaceType:
		return ref + " = nil"
	case *ast.ChanType:
		return ref + " = nil"
	case *ast.FuncType:
		return ref + " = nil"
	}
	return ""
}

// ptrResetLine returns the statement that resets a pointer field.
// For pointers to primitives the pointee is zeroed; for everything else
// Reset() is called on the pointer value if the interface is satisfied.
func ptrResetLine(ref string, inner ast.Expr) string {
	if id, ok := inner.(*ast.Ident); ok {
		if zero, ok := primitiveZero[id.Name]; ok {
			return fmt.Sprintf("if %s != nil { *%s = %s }", ref, ref, zero)
		}
	}
	return fmt.Sprintf("if %s != nil { if _r, _ok := any(%s).(interface{ Reset() }); _ok { _r.Reset() } }", ref, ref)
}
