-- +goose Up
CREATE TABLE IF NOT EXISTS gauges (
    name VARCHAR(255) PRIMARY KEY,
    value DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS counters (
    name VARCHAR(255) PRIMARY KEY,
    value BIGINT NOT NULL DEFAULT 0
);

-- +goose Down
DROP TABLE IF EXISTS gauges;
DROP TABLE IF EXISTS counters;
