// Code generated by reset; DO NOT EDIT.

package audit

// Reset resets all fields of Event to their zero values.
func (e *Event) Reset() {
	if e == nil {
		return
	}
	e.TS = 0
	e.Metrics = e.Metrics[:0]
	e.IPAddress = ""
}
